### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by CDMIUB** [stephan192/dwdwfsapi#2]
The quickstart example returns nothing. 

If the cell Name is given instead of the numeric id, the ows Feature request returns but does not contain a property "WARNCELLID" and line 245 raises:
Illegal property name: WARNCELLID for feature type dwd:Warngebiete_Gemeinden

WARNCELLID seems to be no longer supported

Instead AGS (digits 2-9 of warncell id) TYPE (first digit of warncell id) must be used, apparently

**Comment by martin3000** [comment]
In the query dwd:Warngebiete_Gemeinden/Kreise, the WARNCELLID is no longer returned.

**Comment by martin3000** [comment]
In the module core.py, change the line 
`query += f"&CQL_FILTER={kwargs['cql_filter']}"`
to
`query += f"&CQL_FILTER%3D{kwargs['cql_filter']}"`

**Comment by stephan192** [comment]
The problem is that DWD did a lot of, in my opinion bad, changes.
- WARNCELLID was replaced by FID. But: WARNCELLID was unique over all tables (Gemeinden, Kreise, Binnenseen, See), FID is not unique over all tables.
- The FID attribute is not part of the Warning info, so search must be done by name.
- The table containing the "Gemeinde" warnings dwd:Warnungen_Gemeinden cannot be queried anymore.

I'm currently testing a version which only supports Landkreise, due to the given constrains.

**Comment by martin3000** [comment]
Are these changes documented?
Here https://www.dwd.de/DE/leistungen/warnungen/aenderungen_herbst2021.html?nn=16102&lsbId=397560 they write about upcoming changes in autumn and the warncellid. This does not sound like they want to drop the warncellid. Maybe it is only bug in the DWD software?

**Comment by martin3000** [comment]
I cannot query the Warnungen by FID:
https://maps.dwd.de/geoserver/dwd/ows?service=WFS&version=2.0.0&request=GetFeature&typeName=dwd%3AWarnungen_Landkreise&CQL_FILTER=FID%3D304&OutputFormat=application/json

**Comment by stephan192** [comment]
That what i meant with:
> The FID attribute is not part of the Warning info, so search must be done by name.

My current status:
- It seems as if the warncell id is part of the `id` field when quering for regions. Example result `"id": "Warngebiete_Kreise.103158000"`
https://maps.dwd.de/geoserver/dwd/ows?service=WFS&version=2.0.0&request=GetFeature&typeName=dwd:Warngebiete_Kreise&OutputFormat=application/json
- The warncell id is also part of the `id` field when quering for warnings. Example result `"id": "Warnungen_Landkreise.109576000.2.49.0.1.276.DWD.PVW.1622966655491.0.3"`
https://maps.dwd.de/geoserver/dwd/ows?service=WFS&version=2.0.0&request=GetFeature&typeName=dwd:Warnungen_Landkreise&OutputFormat=application/json
- So the solution is retrieving the whole tables and searching in Python.

Still unresolved:
- The table `dwd:Warnungen_Gemeinden` is missing, so warnings "auf Gemeindeebene" cannot be queried currently.

I think DWD messed up a lot.
Should i publish an update or should we wait for DWD to fix their error?

**Comment by martin3000** [comment]
As of https://geoportal.sachsen.de/cps/capabilities_viewer.html?url=https%3A%2F%2Fmaps.dwd.de%2Fgeoserver%2Fwfs%3FSERVICE%3DWFS%26VERSION%3D2.0.0%26REQUEST%3DGetCapabilities , the feature is dwd:Warnungen_Gemeinden_vereinigt :

https://maps.dwd.de/geoserver/dwd/ows?service=WFS&version=2.0.0&request=GetFeature&typeName=dwd:Warnungen_Gemeinden_vereinigt&OutputFormat=application/json&CQL_FILTER=IDENTIFIER%3D%272.49.0.1.276.0.DWD.PVW.1622965080000.c104d27b-4dd0-4bd0-af7b-714f2f09801b.DEU%27

**Comment by martin3000** [comment]
It is very strange that there is no blog post about that changes.

**Comment by stephan192** [comment]
The table `dwd:Warnungen_Gemeinden_vereinigt` is not new. It exists since i started the development of this api.
The problem with `dwd:Warnungen_Gemeinden_vereinigt` is that the warnings in this table do not contain any information to link the warnings to regions defined in `dwd:Warngebiete_Gemeinden`.

**Comment by martin3000** [comment]
In the capabilities document, Warnungen_Gemeinden is not defined. Maybe it was not official?
Warnungen_Landkreise can be directly accessed by AREADESC filter: CQL_FILTER=AREADESC:'Saale-Holzland-Kreis'

**Comment by stephan192** [comment]
But then the table `dwd:Warngebiete_Gemeinden` doesn't make sense.
I think i will make a fix, which works for everyting execpt "Gemeinden".

**Comment by martin3000** [comment]
I changed the code and this works for Kreise:
`    def __generate_query(self, identifier):
        self.__query = {
                        "typeName": "dwd:Warnungen_Landkreise"
                    }
        self.__query[
                       "CQL_FILTER"
                    ] = f"AREADESC='{identifier}'"`

**Comment by CDMIUB** [comment]
Wow, what a lively community in this project!
I have poke a lot around in den dwd geoserver and it seems they erased WARNCELLID from all layers. And not only the layer dwd:Warnungen_Gemeinden is missin on the geoserver, but also, in the json-file for use in the WarnApp -  where WARNCELLID is still the dictionary key - no WARNCELLIDs starting with "8" for type "Gemeine" (municipality) are currently reported.
I seem the have given up reporting my individual municipalities "Gemeine", alt all.
I have sent a request to opendata@dwd.de ans asked them to clear up, whether this is a malfunction, an error or an intentional change (which is not yet reflected in their documentation)

BTW: Still having the layer "dwd:Warngebiete_Gemeinden" makes sense, since one can match the individual municipality area polyons ("Gemeinde") to the joint municipality warning areas ("Gemeinden_vereinigt") to determine if a warning is issued for an individual municipality. This is a standard opertation for a geospacial information system and easy in theory but would be an **completely unnecessary** complication for any project like this.

**Comment by stephan192** [comment]
I've just released v1.0.4 of the api to PyPi. It works with "Landkreise". I'll create a pull-request on HA.

@CDMIUB I'll leave this issue open until you report back what DWD answered to your email.

**Comment by Hummel95** [comment]
Hey there,
I got a reply to my email (sent it around the same time):

"es handelt sich wirklich um einen Fehler, der seit letztem Donnerstag auftritt.
Der Geoserver liefert die WanrCell-IDs bei diesem Layer nicht mehr auf.
Auch unser Feuerwehrinformationssystem ist davon betroffen.
Leider ist die Ursache noch nicht gefunden.

Ich hoffe, dass wir im Laufe des Tages das Problem lösen können."
(It's a bug on dwd's side which they are hoping to fix today).

Thanks for your effort though! I guess the change should be rolledback.

**Comment by stephan192** [comment]
Now they fixed their error. All work done for nothing.
But both versions (1.0.3 and 1.0.4) work with the fixed api.
1.0.4 creates higher loads on the dwd servers but may be more robust.

**Comment by nibblerrick** [comment]
Although all the work was in the end "fürn Ar..." a big thank you to your guys for going to fix it so quickly!
