### ISSUE TITLE
Request: Integration of ODL-INFO for HA

### ISSUE THREAD

**Issue by f45tb00t** [stephan192/dwdwfsapi#3]
Hello Stephan,

sorry to reach you this way, but github removed the possibility to write messages to users.

As my coding skills are very limited I would like to ask if if you might have fun for another nice integration for HA. 

Since your DWD Integration is kinda nice I thought you might be interested in another statistics:

https://odlinfo.bfs.de/DE/index.html

Do you think its feasible to implement this? Basically they provide data of radiation-level checks. 

Kind regards

fb

**Comment by stephan192** [comment]
Hi f45tb00t,
after having a quick look i think it should be possible to integrate ODL-Info into Home Assistant.
But in the foreseeable future i don't have enough spare time to implement things like that.
