### ISSUE TITLE
Nearest warncell based on location?

### ISSUE THREAD

**Issue by andarotajo** [stephan192/dwdwfsapi#4]
Hey, I've been using this project through Home Assistant recently and wondered, if it's possible to retrieve the nearest warncell id based on the given location (longitude and latitude)?

Basically I don't want to limit my automations to specific locations but have them give me the warnings wherever I am (in Germany)

**Comment by stephan192** [comment]
In pricipal this is possible.

If you have a closer look at the data for the "Gemeinde-Warnungen" you will see that for each warncell geometric data (corners of the warncell polygon) are provided. With this information it should be possible to calculate the warncell you are in.
https://maps.dwd.de/geoserver/dwd/ows?service=WFS&version=2.0.0&request=GetFeature&typeName=dwd%3AWarngebiete_Gemeinden&OutputFormat=application/json

But: This is a lot of work with little to no benefit, therefore i will not implement this feature.
Feel free to make a pull request.
